import smtplib #importing smtplib

class sending_mail: #creating class

    def __init__(self, to, cc, bcc):
    
        """Initialize the instance where the email address stored"""

        self.to = to
        self.cc = cc
        self.bcc = bcc

    def sending(self):
        
        """Sending mail through python by calling sending method.
        it takes the email address as an arguments after sending mail it prints 
        a message "Sucessfully sent" in terminal"""

        #store from mail address and password in variables
        from_mail = 'radhamaredi1995@gmail.com'
        password = 'yqozteemfxuiurzs'

        #store the body and subject of the mail in variables
        subject = "Sending mail using Python"
        body = "Hi! i am Radha, this mail generated by python"
        
        #join the all sending address(to,cc) and subject and body
        message = f'To: {self.to} \rCc: {", ".join(self.cc)} \r\nSubject: {subject}\n\n{body}'
        
        #puts the connection to the SMTP server into SSL mode.
        smtp_server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        smtp_server.login(from_mail, password)      #login the mail
        #sending the mail
        smtp_server.sendmail(from_mail, [self.to] + self.cc + self.bcc, message) 
        smtp_server.close()  #close the server 
        #print some text to know whether our text sent or not
        print ("Successfully sent")

#creating object of the class and give the to address as an arguments
email1 = sending_mail('vibha.rawan@neosoftmail.com',['grandheraj68@gmail.com'],['mailto:lakshmi73862@gmail.com'])
 
email1.sending() #calling sunding method